:: Generated by mc-utilities

@echo off

set PACK_NAME=

title %PACK_NAME% Bedrock Edition Installation

cd /D "%~dp0"

set RESOURCE_FOLDER=%LOCALAPPDATA%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\resource_packs

echo 				.
echo ==============================
echo Making resource pack folders...
echo ==============================
echo 				.

md "%RESOURCE_FOLDER%"

echo
echo ==============================
echo Copying the files...
echo ==============================
echo

echo Done!

echo 				.

title Finished installing!

pause